services:
  postgres:
    image: pgvector/pgvector:pg16
    platform: linux/amd64
    container_name: devops_pr_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: devops_agent
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d devops_agent"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: